---
version: "3"

services:
    apache:
        image: httpd:2.4
        ports: 
            - "7070:80"
                   
     nginx:
        image: nginx:latest
        ports: 
            - "6060:80"