---
version: "3"

services:

  apache:
   image: httpd:2.4
   ports: 
    - "7070:80"
                   
  nginx:
   image: nginx:latest
   ports: 
    - "6060:80"

  wordpress:
    image: wordpress
    restart: always
    ports:
      - "5050:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_DB_NAME: proyecto

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: proyecto
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
